// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPVbie1t0nrPYgvKmr9RFD8Rxk0s_Rkco',
    appId: '1:623346185585:web:a70c8bdd2b8a575a36f2d0',
    messagingSenderId: '623346185585',
    projectId: 'fasum-dimas-5e6cd',
    authDomain: 'fasum-dimas-5e6cd.firebaseapp.com',
    storageBucket: 'fasum-dimas-5e6cd.firebasestorage.app',
    measurementId: 'G-TNF6R92N33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5JbxLBndDDjBBF07R9Ps4QoMgNTkfx4',
    appId: '1:623346185585:android:b77a0379c372523136f2d0',
    messagingSenderId: '623346185585',
    projectId: 'fasum-dimas-5e6cd',
    storageBucket: 'fasum-dimas-5e6cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCufyplHNChpZRhL7bDutJuZo22KliJc0c',
    appId: '1:623346185585:ios:d836baa33c9afaed36f2d0',
    messagingSenderId: '623346185585',
    projectId: 'fasum-dimas-5e6cd',
    storageBucket: 'fasum-dimas-5e6cd.firebasestorage.app',
    iosBundleId: 'com.example.fasumDimas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCufyplHNChpZRhL7bDutJuZo22KliJc0c',
    appId: '1:623346185585:ios:d836baa33c9afaed36f2d0',
    messagingSenderId: '623346185585',
    projectId: 'fasum-dimas-5e6cd',
    storageBucket: 'fasum-dimas-5e6cd.firebasestorage.app',
    iosBundleId: 'com.example.fasumDimas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPVbie1t0nrPYgvKmr9RFD8Rxk0s_Rkco',
    appId: '1:623346185585:web:f4c90b0a93988f4636f2d0',
    messagingSenderId: '623346185585',
    projectId: 'fasum-dimas-5e6cd',
    authDomain: 'fasum-dimas-5e6cd.firebaseapp.com',
    storageBucket: 'fasum-dimas-5e6cd.firebasestorage.app',
    measurementId: 'G-VXX049W290',
  );

}